language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-es6-library-boilerplate' ]; then cd .. && eval "mv $currentfolder generator-es6-library-boilerplate" && cd generator-es6-library-boilerplate; fi
